name: Release Beta

on:
  pull_request:
    branches: [ v1.x ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 34 ]
        target: [ android-34 ]
        java-version: [ '21' ]
        build-tools: [ '31.0.0' ]

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: gradle

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      # Grant permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Create local.properties
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo ${{ vars.UPDATE_CHANNEL_BETA }} >> local.properties
          echo ${{ vars.PROJECT_ID }} >> local.properties
          echo ${{ vars.NATIVE_AD_ID_POST }} >> local.properties
          echo ${{ vars.NATIVE_AD_ID_SEARCH }} >> local.properties

      # Create google-services.json
      - name: Create google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES | base64 -di > app/google-services.json

      # Create google-services.json
      - name: Create codemonk_service_key.json
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
        run: |
          mkdir -p core/util/src/main/res/raw
          echo $SERVICE_KEY | base64 -di > core/util/src/main/res/raw/codemonk_service_key.json

      # Build APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # Sign APK
      - name: Sign APK
        uses: ilharp/sign-android-release@nightly
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.KEY_STORE }}
          keyAlias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      # Run tests
      - name: Run tests
        run: ./gradlew testReleaseUnitTest

      # Generate release version name and tag
      - name: Generate version name and tag
        id: vars
        run: |
          VERSION_NAME=$(./gradlew -q printVersionName)
          TAG_NAME=$(echo "v$VERSION_NAME-rc${{ vars.RC_VERSION }}" | sed 's/ /_/g')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      # Rename APK
      - name: Rename APK
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/outputs/apk/release/Code_Monk_v${{ env.VERSION_NAME }}-${{ vars.RC_VERSION }}.apk

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: v${{ env.VERSION_NAME }}-${{ vars.RC_VERSION }}
          prerelease: true
          draft: true
          files: app/build/outputs/apk/release/Code_Monk_v${{ env.VERSION_NAME }}-${{ vars.RC_VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # Increment rc version
      - name: Bump  version
        uses: action-pack/increment@v2
        id: increment
        with:
          name: 'RC_VERSION'
          token: ${{ secrets.TOKEN }}